Align azure timeout with s3
man-group/ArcticDB pull request #1487
Opened 2024-04-10 17:07 UTC by phoebusm

#### Reference Issues/PRs

Fix https://github.com/man-group/ArcticDB/issues/1026
#### What does this implement or fix?
Azure timeout has been incorrectly set to 60000ms. It needs to be addressed
#### Any other comments?

#### Checklist

<details>
  <summary>
   Checklist for code changes...
  </summary>
 
 - [ ] Have you updated the relevant docstrings, documentation and copyright notice?
 - [ ] Is this contribution tested against [all ArcticDB's features](../docs/mkdocs/docs/technical/contributing.md)?
 - [ ] Do all exceptions introduced raise appropriate [error messages](https://docs.arcticdb.io/error_messages/)?
 - [ ] Are API changes highlighted in the PR description?
 - [ ] Is the PR labelled as enhancement or bug so it appears in autogenerated release notes?
</details>

2024-04-10 17:25 UTC, poodlewars requested changes

2024-04-10 17:25 UTC, poodlewars commented on cpp/arcticdb/storage/azure/azure_storage.cpp
> +                upload_option_.TransferOptions.Concurrency = max_connections;
?

2024-04-10 17:33 UTC, phoebusm commented on cpp/arcticdb/storage/azure/azure_storage.cpp
> +                upload_option_.TransferOptions.Concurrency = max_connections;
Sorry it doesn't show up in my diff. 😢

2024-04-11 10:05 UTC, poodlewars approved these changes
As discussed this is fine for now but I think we should actually drop the timeout completely - there are quite a few cases where a request might read a very large object and timeout.

2024-04-16 13:07 UTC, merged