WIP Read as arrow
man-group/ArcticDB pull request #1831
Opened 2024-09-12 12:24 UTC by willdealtry

WIP read dataframe as Arrow arrays

2024-10-16 15:36 UTC, wuxianliang commented
Dear friend, Great Job! I have saved all stocks data in ArcticDB, I would like to read the data from SSD directly into arrow table. Then we can query with DuckDB, LanceDB even KuzuDB in memory. As I understand finally maybe use ArcticDB zero-copy like this?
``` python
import arcticdb
import duckdb
import lancedb
import kuzudb

......

arrow_table = lib.read("Symbol", output_format=OutputFormat.ARROW).data

duckdb.sql("SELECT * FROM arrow_table")
lancedb.create_table("Symbol", arrow_table, schema=schema)
kuzudb.execute("COPY Symbol FROM arrow_table")
```

2024-10-17 10:40 UTC, willdealtry commented
> Dear friend, Great Job! I have saved all stocks data in ArcticDB, I would like to read the data from SSD directly into arrow table. Then we can query with DuckDB, LanceDB even KuzuDB in memory. As I understand finally maybe use ArcticDB zero-copy like this?
> 
> ```python
> import arcticdb
> import duckdb
> import lancedb
> import kuzudb
> 
> ......
> 
> arrow_table = lib.read("Symbol", output_format=OutputFormat.ARROW).data
> 
> duckdb.sql("SELECT * FROM arrow_table")
> lancedb.create_table("Symbol", arrow_table, schema=schema)
> kuzudb.execute("COPY Symbol FROM arrow_table")
> ```

Yes that's exactly right. I'm very pleased to hear that you are excited about this piece of work!

2024-11-01 14:10 UTC, wuxianliang commented
Does read_batch method support read_as_arrow too? Sometimes I wish to analysis all symbols in a daterange.

2025-03-20 13:49 UTC, jamesmunro commented on cpp/arcticdb/version/python_bindings.cpp
> +        .value("PARQUET", OutputFormat::PARQUET);
Drop this parquet option for now?

2025-03-20 14:03 UTC, jamesmunro commented on cpp/arcticdb/version/python_bindings.cpp
>          .value("PANDAS", OutputFormat::PANDAS)
`PANDAS` is probably fine as a name, but worth considering that we'll want to add an arrow-backed pandas dataframe option later.

2025-06-05 07:08 UTC, IvoDD commented on cpp/arcticdb/version/python_bindings.cpp
> +        .value("PARQUET", OutputFormat::PARQUET);
Done

2025-06-05 07:09 UTC, IvoDD commented on python/arcticdb/version_store/_store.py
> +        read_options.set_output_format(kwargs.get("output_format") or OutputFormat.PANDAS)
Will do these changes in frontend PR as discussed offline. Will have a new `RuntimeLibraryOptions` so we don't have to specify the output format on every request.

2025-06-06 07:00 UTC, IvoDD commented on cpp/arcticdb/pipeline/read_frame.cpp
> +                        truncate_rows = get_truncate_range_from_index(index_column, time_range.first, time_range.second);
This change is mostly whitespace. Only removes the `current_row_range` and the arguments it passes to `get_truncate_range_from_index`.

This is to avoid a segfault in existing tests. There are many more issues with this logic (off by one errors etc.). This will be reworked in a future PR so no need to spend too much time on review.

2025-06-06 07:02 UTC, IvoDD commented on cpp/arcticdb/pipeline/read_frame.cpp
> +            SliceDataSink sink(buffer.bytes_at(offset, tot_size), tot_size);
This is required to handle the case where `offset` is not in the first block of the `buffer`

2025-06-06 07:05 UTC, IvoDD commented on cpp/arcticdb/pipeline/pipeline_utils.hpp
> +            util::check(output_format == OutputFormat::PANDAS, "Only Pandas output format is supported for read_result_from_single_frame");
`read_result_from_single_frame` is only used for lib tool utilities and operations like `read_index`.

2025-06-06 08:01 UTC, IvoDD commented on cpp/arcticdb/version/local_versioned_engine.cpp
> +                })
Only whitespace

2025-06-06 13:48 UTC, IvoDD commented on cpp/arcticdb/pipeline/frame_slice.hpp
> +    return row >= range.first && row <= range.second;
`contains` is only used in `truncation` logic.
This makes more sense to revert to exclusive end. Will do in the follow up PR to fix truncation.

2025-06-11 15:00 UTC, alexowens90 requested changes

2025-06-11 15:00 UTC, alexowens90 commented on cpp/arcticdb/CMakeLists.txt
> +        pipeline/read_pipeline.cpp
nit: alphabetical order

2025-06-11 15:00 UTC, alexowens90 commented on cpp/arcticdb/codec/encode_v1.cpp
> +                util::check(!is_arrow_output_only_type(data_type), "Attempts to encode an output only type {}", data_type);
```suggestion
                util::check(!is_arrow_output_only_type(column.type()), "Attempts to encode an output only type {}", data_type);
```
and same in `encode_v2.cpp`

2025-06-11 15:00 UTC, alexowens90 commented on cpp/arcticdb/column_store/column.cpp
> +    if(!is_sparse()) { // TODO: We need to also do truncation on sparse data
Is there a consolidated list of remaining Arrow work somewhere? Would be good to track all things like this in one place so we don't forget anything

2025-06-11 15:00 UTC, alexowens90 commented on cpp/arcticdb/arrow/array_from_block.hpp
> +    // We use `int32_t` dictionary keys because pyarrow doesn't work with unsigned dictionary keys:
Discussing out of band using int64 for more resilience to massive strings, and adding an optimisation later to use int32 where possible (i.e. if a column would have <2^32 bytes of strings in every record batch)

2025-06-11 15:00 UTC, alexowens90 commented on cpp/arcticdb/entity/types.hpp
> +DATA_TYPE_TAG(UTF_DYNAMIC32, std::uint32_t)
Should this be signed?

2025-06-11 15:00 UTC, alexowens90 commented on cpp/arcticdb/pipeline/frame_slice.hpp
> - */
Seems still needed

2025-06-11 15:00 UTC, alexowens90 commented on cpp/arcticdb/pipeline/pandas_output_frame.cpp
> +                                log::version().error("Unexpected nullptr to DecRef in PandasOutputFrame destructor");
Was the check throwing in some cases before? Do we ever see this error?

2025-06-11 15:00 UTC, alexowens90 commented on cpp/arcticdb/util/bitset.hpp
> +    return (size + 63) / 64 * sizeof(uint64_t);
Shouldn't this return 1 if `size` is 1-8, 2 if `size` is 9-16, etc? If not worth a comment as to why

2025-06-11 15:00 UTC, alexowens90 commented on cpp/arcticdb/util/bitset.hpp
> +    return (size + 63) / 64 * sizeof(uint64_t);
Oh is it padded out to the nearest 8 bytes? Is that an Arrow thing, or an us thing?

2025-06-11 15:00 UTC, alexowens90 commented on cpp/arcticdb/util/bitset.hpp
> +        size_t bit_idx = bit_pos % 64;
These `size_t`s should all be `uint64_t`, and can use `std::div` here to get the quotient and remainder in one operation

2025-06-11 15:00 UTC, alexowens90 commented on cpp/arcticdb/util/bitset.hpp
> +}
Not for this PR, but on the TODO list of outstanding work, we should add a microbenchmark for this and make sure it's optimal. For example, `bit_pos`, and therefore `word_idx` are monotonically increasing, but the compiler can't know this. So it might be possible to improve the performance by building up each `uint64_t` and then just assigning once to `dest_ptr[word_idx]`.
There are also more efficient set-bit visitors possible, at the cost of a bit more code:
https://github.com/tlk00/BitMagic/tree/master/samples/bvsample25

2025-06-11 15:00 UTC, alexowens90 commented on cpp/arcticdb/version/version_map_entry.hpp
> +            strm << fmt::format("    {} - {}", tombstone.first, tombstone.second) << "\n";
nit: Could fold a lot of these newlines into adjacent strings

2025-06-11 15:00 UTC, alexowens90 commented on python/tests/unit/arcticdb/version_store/test_arrow.py
> +    result = convert_pandas_categorical_to_str(vit.data.to_pandas())
I assume this means pyarrow to_pandas converts string columns to categoricals?

2025-06-11 15:00 UTC, alexowens90 commented on python/tests/unit/arcticdb/version_store/test_arrow.py
> +@pytest.mark.parametrize("start_offset,end_offset", [(2, 3), (3, 75), (4, 32), (0, 99), (7, 56)])
Could also test with the first, second, and both offsets being `None`

2025-06-11 15:00 UTC, alexowens90 commented on python/tests/unit/arcticdb/version_store/test_arrow.py
> +def test_date_range(lmdb_version_store_v1, start_offset, end_offset):
Would be good to run this with `lmdb_version_store_tiny_segment` as well (might need your truncate PR to pass)

2025-06-11 15:00 UTC, alexowens90 commented on python/tests/unit/arcticdb/version_store/test_arrow.py
> +    assert_frame_equal(result, expected)
Before making publicly available we should make sure all of the processing pipeline tests run with both Pandas and Arrow as the output formats

2025-06-11 15:00 UTC, alexowens90 commented on python/tests/unit/arcticdb/version_store/test_arrow.py
> +    vit = lib.read("arrow", _output_format=OutputFormat.ARROW)
Can we also assert the existence and correct population of the validity bitmaps in the returned record batches?

2025-06-11 15:00 UTC, alexowens90 commented on python/tests/unit/arcticdb/version_store/test_arrow.py
> +    vit = lib.read("arrow", _output_format=OutputFormat.ARROW)
Can we assert that the type of `x` in all of the returned record batches is `float64`?
Presumably this is a requirement of the pyarrow table format? i.e. we couldn't return a list of record batches where `x` is `int64` in the first and `float64` in the second and have pyarrow recognise it as a valid table? Just thinking out loud about potential performance optimisations with dynamic schema

2025-06-11 15:00 UTC, alexowens90 commented on cpp/arcticdb/python/adapt_read_dataframe.hpp
> +inline py::tuple adapt_read_df(ReadResult&& ret, std::any* const handler_data) {
Looks like `handler_data` is never `nullptr`, so can be passed by reference?

2025-06-11 15:00 UTC, alexowens90 commented on cpp/arcticdb/python/python_utils.hpp
> +inline py::list adapt_read_dfs(std::vector<std::variant<ReadResult, DataError>>&& r, std::any* const handler) {
```suggestion
inline py::list adapt_read_dfs(std::vector<std::variant<ReadResult, DataError>>&& r, std::any& handler) {
```

2025-06-11 15:00 UTC, alexowens90 commented on cpp/arcticdb/version/python_bindings.cpp
> +        //.def(py::init<const SegmentInMemory&, OutputFormat output_format, std::shared_ptr<BufferHolder>>())
nit: remove

2025-06-11 15:00 UTC, alexowens90 commented on cpp/arcticdb/version/python_bindings.cpp
> +        .def_property_readonly("names", &ArrowOutputFrame::names)
Seems to be unused

2025-06-11 15:00 UTC, alexowens90 commented on cpp/arcticdb/version/version_core.cpp
> +    auto frame = allocate_frame(pipeline_context, read_options.output_format());
We could optimise in future to move buffers from the processed segments into the output frame rather than memcpy them

2025-06-11 15:00 UTC, alexowens90 commented on cpp/arcticdb/pipeline/read_frame.cpp
> +        bitset_unpacked_size(sparse_map.count() * sizeof(uint64_t)),
```suggestion
        bitset_unpacked_size(sparse_map.size() * sizeof(uint64_t)),
```

2025-06-11 15:00 UTC, alexowens90 commented on cpp/arcticdb/column_store/column.hpp
> +    static void hash_combine(std::size_t& seed, std::size_t value) {
nit: folly (and presumably boost) has hashing combinations to avoid hand-rolling our own

2025-06-11 15:00 UTC, alexowens90 commented on cpp/arcticdb/column_store/column.hpp
> +    size_t offset_;
It took me a while to work out what this means, maybe a rename to `offset_bytes_` and a comment.
Using this struct as a map key also seems quite weird at the moment, maybe it will become clear by the time I finish reading the PR though

2025-06-11 15:00 UTC, alexowens90 commented on cpp/arcticdb/column_store/column.hpp
> +    OFFSET,
This word is so overloaded, I'm guessing this is the dict keys in a string column?
If we use int64 as the dict keys, there is a possible future optimisation where we don't have an extra buffer, and just reuse the original column buffer, overwriting our string pool offsets with the dict keys to avoid an extra allocation. Would only work for single-block columns, but that is most of our data

2025-06-11 15:00 UTC, alexowens90 commented on cpp/arcticdb/entity/read_result.hpp
> +            return pipelines::PandasOutputFrame{result.frame_, output_format};
Is the output format really required in the `PandasOutputFrame` ctor? Seems like an error to pass anything but `OutputFormat::PANDAS` in?

2025-06-11 15:00 UTC, alexowens90 commented on cpp/arcticdb/entity/read_result.hpp
> +    OutputFormat output_format;
We could get rid of this and use `isinstance` on the `frame_data` member in the Python layer to avoid duplicating information

2025-06-11 15:00 UTC, alexowens90 commented on cpp/arcticdb/util/type_handler.hpp
> +    std::array<TypeHandlerMap, 4> handlers_;
Previous impl seems better? (and on line 123 as well)

2025-06-11 15:00 UTC, alexowens90 commented on cpp/arcticdb/arrow/arrow_output_frame.cpp
> +    if(data_->empty())
```suggestion
    if(!data_ || data_->empty())
```

2025-06-11 15:00 UTC, alexowens90 commented on cpp/arcticdb/arrow/arrow_output_frame.cpp
> +std::vector<RecordBatchData> ArrowOutputFrame::extract_record_batches() {
I guess return an empty vector if `data_` is null

2025-06-11 15:00 UTC, alexowens90 commented on cpp/arcticdb/arrow/arrow_utils.cpp
> +    util::check(total_blocks == column_blocks * num_columns, "Expected regular block size");
nit: This can be checked as soon as the 3 variables are assigned

2025-06-11 15:00 UTC, alexowens90 commented on cpp/arcticdb/arrow/array_from_block.hpp
> +        const auto bitmap_size = bitmap_buffer.block(0)->bytes() / sizeof(uint32_t);
Why the division? Bitmap buffers seemed to be aligned to 8-bytes before?

2025-06-11 15:00 UTC, alexowens90 commented on cpp/arcticdb/arrow/array_from_block.hpp
> +    const auto offset_buffer_size = string_offsets.block(0)->bytes() / sizeof(int32_t);
```suggestion
    const auto offset_buffer_value_count = string_offsets.block(0)->bytes() / sizeof(int32_t);
```

2025-06-11 15:00 UTC, alexowens90 commented on cpp/arcticdb/arrow/array_from_block.hpp
> +    sparrow::u8_buffer<int32_t> dict_keys_buffer{reinterpret_cast<int32_t *>(block.release()), block_size};
Won't this `block` be int64 offsets into our stringpool? I'm clearly missing something about this implementation

2025-06-11 15:00 UTC, alexowens90 commented on cpp/arcticdb/arrow/array_from_block.hpp
> +    sparrow::u8_buffer<int32_t> dict_keys_buffer{reinterpret_cast<int32_t *>(block.release()), block_size};
Oh I think I get it, the conversions is taken care of by the `ArrowStringHandler`?

2025-06-11 15:00 UTC, alexowens90 commented on cpp/arcticdb/arrow/arrow_handlers.cpp
> +    auto dest_ptr = reinterpret_cast<uint32_t*>(dest_column.bytes_at(mapping.offset_bytes_, source_column.row_count() * sizeof(uint32_t)));
This mixing of `uint32_t` and `int32_t` seems like a recipe for disaster. Can we stick a single `using` statement for the raw type we are using for dict keys in Arrow string columns somewhere and use it everywhere? That way we can also trivially flip to `int64_t` as well

2025-06-11 15:00 UTC, alexowens90 commented on cpp/arcticdb/arrow/arrow_handlers.hpp
> +        DataType::ASCII_DYNAMIC64, DataType::UTF_DYNAMIC64, DataType::ASCII_FIXED64, DataType::UTF_FIXED64};
This class has registered to handle all of our support internal string types, but in reality `ArrowStringHandler::convert_type` will only actually handle `UTF_DYNAMIC64`

2025-06-11 15:00 UTC, alexowens90 commented on cpp/arcticdb/arrow/arrow_handlers.cpp
> +    }
I don't think this is correct except in the (unlikely) case that iteration through `unique_offsets` matches the insertion order into it

2025-06-11 15:05 UTC, alexowens90 commented
Prior to releasing, we should ensure:

- we are definitely zero-copy on the direct-read path, and only incur one additional copy on the processing pipeline path
- we are correctly transferring ownership of the underlying buffers, so that there is no unexpected memory overhead or leak associated with reading an Arrow structure from ArcticDB vs creating it in pyarrow or similar
- we have profiled (and included microbenchmarks/ASV benchmarks for critical regions) and optimised as far as possible

2025-06-11 15:35 UTC, IvoDD commented on cpp/arcticdb/column_store/column.cpp
> +    if(!is_sparse()) { // TODO: We need to also do truncation on sparse data
Yes I've kept those as tasks on the arrow epic. This specific TODO corresponds to 9288960436 ticket.

2025-06-11 15:35 UTC, IvoDD commented on cpp/arcticdb/arrow/array_from_block.hpp
> +    // We use `int32_t` dictionary keys because pyarrow doesn't work with unsigned dictionary keys:
Agreed, will do

2025-06-11 15:37 UTC, IvoDD commented on cpp/arcticdb/entity/types.hpp
> +DATA_TYPE_TAG(UTF_DYNAMIC32, std::uint32_t)
It is converted from unsigned to signed in the ArrowStringHandler with checks if it will overflow.

As per other discussion I think we should just stick to using the largest possible types and add optimizations later. I.e. this would mean we can reuse the `UTF_DYNAMIC64`.

2025-06-11 15:38 UTC, IvoDD commented on cpp/arcticdb/pipeline/pandas_output_frame.cpp
> +                                log::version().error("Unexpected nullptr to DecRef in PandasOutputFrame destructor");
We have not seen this error I think. But it is undefined behavior to raise in destructor. That's why replaced with logs.

2025-06-11 15:41 UTC, IvoDD commented on cpp/arcticdb/util/bitset.hpp
> +}
Added a note to the ticket for benchmarking. Also noted there that we should include micro benchmarks for:
- ArrowStringHandler
- ColumnTruncation

2025-06-11 15:43 UTC, IvoDD commented on python/tests/unit/arcticdb/version_store/test_arrow.py
> +    result = convert_pandas_categorical_to_str(vit.data.to_pandas())
yes, we'll need to decide whether we will want to correctly round trip with a plain `pyarrow.to_pandas`. 
I don't think we should as it will be very hard but happy to discuss.

2025-06-11 15:43 UTC, IvoDD commented on python/tests/unit/arcticdb/version_store/test_arrow.py
> +@pytest.mark.parametrize("start_offset,end_offset", [(2, 3), (3, 75), (4, 32), (0, 99), (7, 56)])
Will be done in follow up truncation PR

2025-06-11 15:44 UTC, IvoDD commented on python/tests/unit/arcticdb/version_store/test_arrow.py
> +def test_date_range(lmdb_version_store_v1, start_offset, end_offset):
yes, doing this in follow up truncation pr. Would not pass in this one.

2025-06-11 15:44 UTC, IvoDD commented on python/tests/unit/arcticdb/version_store/test_arrow.py
> +    assert_frame_equal(result, expected)
Will add a ticket for that

2025-06-11 15:47 UTC, IvoDD commented on python/tests/unit/arcticdb/version_store/test_arrow.py
> +    vit = lib.read("arrow", _output_format=OutputFormat.ARROW)
I suspect validity bitmaps are a bit broken so have refrained from thoroughly testing them. 

We should add such tests when doing the sparse data ticket 9288960436

2025-06-11 15:50 UTC, IvoDD commented on cpp/arcticdb/python/adapt_read_dataframe.hpp
> +inline py::tuple adapt_read_df(ReadResult&& ret, std::any* const handler_data) {
I think it could be (and there was a reason for doing it this way when discussing this with Vasil with respect to null handling). I'll look and come back

2025-06-11 15:53 UTC, IvoDD commented on cpp/arcticdb/version/python_bindings.cpp
> +        .def_property_readonly("names", &ArrowOutputFrame::names)
ah yes the `names` bit is unused

2025-06-11 15:54 UTC, IvoDD commented on cpp/arcticdb/version/version_core.cpp
> +    auto frame = allocate_frame(pipeline_context, read_options.output_format());
I'll add a ticket

2025-06-11 15:59 UTC, IvoDD commented on cpp/arcticdb/column_store/column.hpp
> +    OFFSET,
Not exactly the dict keys but the offsets in the string pool. It is slightly different e.g if we have a column:
```
["ab", "c", "ab"]
```

It will get stored for arrow as:
```
column values:       [0, 1, 0]
OFFSET extra buffer: [0, 2, 3]
STRING extra buffer: ["a", "b", "c"]
```

I'm not sure I understand your proposed optimization. Let's chat offline

2025-06-11 16:02 UTC, IvoDD commented on cpp/arcticdb/arrow/array_from_block.hpp
> +    sparrow::u8_buffer<int32_t> dict_keys_buffer{reinterpret_cast<int32_t *>(block.release()), block_size};
yeah the `ArrowStringHandler` attaches the required `ExtraBuffer`s

2025-06-11 16:04 UTC, IvoDD commented on cpp/arcticdb/arrow/arrow_handlers.cpp
> +    }
Ah that's correct. Will rework

2025-06-12 08:54 UTC, alexowens90 commented on cpp/arcticdb/arrow/array_from_block.hpp
> +    // We use `int32_t` dictionary keys because pyarrow doesn't work with unsigned dictionary keys:
I think I had misunderstood the buffer structure for Arrow dict columns, let's discuss

2025-06-12 09:48 UTC, alexowens90 commented on cpp/arcticdb/entity/types.hpp
> +DATA_TYPE_TAG(UTF_DYNAMIC32, std::uint32_t)
Discussed in person, use int32_t

2025-06-12 09:50 UTC, alexowens90 commented on cpp/arcticdb/util/bitset.hpp
> +    return (size + 63) / 64 * sizeof(uint64_t);
Park this until we fully implement sparse data

2025-06-12 10:06 UTC, alexowens90 commented on cpp/arcticdb/pipeline/read_frame.cpp
> +        bitset_unpacked_size(sparse_map.count() * sizeof(uint64_t)),
Park until we're fixing sparse in general

2025-06-12 10:14 UTC, alexowens90 commented on cpp/arcticdb/entity/read_result.hpp
> +            return pipelines::PandasOutputFrame{result.frame_, output_format};
`NATIVE` format used in some C++ tests to avoid a Python dependency, leave in
Add a comment to `PandasOutputFrame` ctor to avoid other people asking this question in future

2025-06-12 10:23 UTC, alexowens90 commented on cpp/arcticdb/arrow/array_from_block.hpp
> +        const auto bitmap_size = bitmap_buffer.block(0)->bytes() / sizeof(uint32_t);
Park until sparse implemented

2025-06-12 10:29 UTC, alexowens90 commented on cpp/arcticdb/arrow/arrow_handlers.hpp
> +        DataType::ASCII_DYNAMIC64, DataType::UTF_DYNAMIC64, DataType::ASCII_FIXED64, DataType::UTF_FIXED64};
Can come later

2025-06-17 13:34 UTC, IvoDD commented on cpp/arcticdb/arrow/arrow_handlers.cpp
> +    }
Used an `std::vector` to keep track of the correct order. Renamed quite a few variables to make logic more clear.

2025-06-17 13:46 UTC, IvoDD commented on cpp/arcticdb/python/adapt_read_dataframe.hpp
> +inline py::tuple adapt_read_df(ReadResult&& ret, std::any* const handler_data) {
There are some python calls like `restore_version` [here](https://github.com/man-group/ArcticDB/blob/becbe4000d61b72b10ffc31c51c9f1a35a213e4a/cpp/arcticdb/version/python_bindings.cpp#L779). There we construct a python read result without requiring any python handler allocations, so will leave as is.

2025-06-17 13:51 UTC, IvoDD commented on cpp/arcticdb/python/python_utils.hpp
> +inline py::list adapt_read_dfs(std::vector<std::variant<ReadResult, DataError>>&& r, std::any* const handler) {
Similar to above for `batch_restore_version` which I slightly changed to use `adapt_read_dfs` to be consistent with other `batch` methods.

2025-06-17 15:28 UTC, IvoDD commented on cpp/arcticdb/entity/read_result.hpp
> +            return pipelines::PandasOutputFrame{result.frame_, output_format};
Turned out the C++ tests did not rely on the NATIVE output format so I removed the `output_format` member of `PandasOutputFrame`

2025-06-17 15:37 UTC, IvoDD commented on cpp/arcticdb/entity/read_result.hpp
> +    OutputFormat output_format;
I'll keep it here to differetiate between NATIVE and PANDAS because on the read result layer we see which handlers we need to use.

Still removing from the python read_result as you're right that it's not needed there.

2025-06-19 10:23 UTC, alexowens90 approved these changes

2025-06-20 08:03 UTC, merged