Make library manager an LRU cache
man-group/ArcticDB pull request #1930
Opened 2024-10-17 08:18 UTC by willdealtry

At the moment as we open more and more libraries we never close them, meaning that we can run out of filehandles.

2024-10-17 08:23 UTC, poodlewars commented
Will this help with the file descriptor exhaustion problem? Given https://github.com/man-group/ArcticDB/pull/1908 aren't we going to hold them open regardless of this change?

2024-10-22 08:32 UTC, alexowens90 requested changes

2024-10-22 08:32 UTC, alexowens90 commented on cpp/arcticdb/CMakeLists.txt
> +            util/test/rapidcheck_lru_cache.cpp)
Remove from other targets

2024-10-22 08:32 UTC, alexowens90 commented on cpp/arcticdb/util/lru_cache.hpp
> +        std::unique_lock lock(mutex_);
Why `unique_lock` over `lock_guard`?

2024-10-22 08:32 UTC, alexowens90 commented on cpp/arcticdb/util/lru_cache.hpp
> +    void put(KeyType key, ValueType value) {
nit: Could pass both args by `const&`, and then only incur the copy cost of `key` in the `else` branch below

2024-10-28 13:09 UTC, willdealtry commented on cpp/arcticdb/util/lru_cache.hpp
> +        std::unique_lock lock(mutex_);
It's a std::shared_mutex

2024-10-29 11:20 UTC, alexowens90 approved these changes

2024-10-29 12:36 UTC, merged