Enhancement 119: Create, read, and drop column stats
man-group/ArcticDB pull request #253
Opened 2023-04-21 09:22 UTC by alexowens90

2023-04-21 09:26 UTC, alexowens90 commented on cpp/arcticdb/processing/aggregation.cpp
> +            col->set_row_data(unique_values - 1);
These changes do not affect the aggregation behaviour, but means that the `SegmentInMemory` row count is accurate.

2023-04-21 09:26 UTC, alexowens90 commented on cpp/arcticdb/storage/lmdb/lmdb_storage-inl.hpp
> +    auto keys = kvs.transform([](const auto& kv){return kv.variant_key();});
This change addresses issue #251

2023-04-21 09:27 UTC, alexowens90 commented on cpp/arcticdb/version/version_store_api.cpp
> +        delete_trees_responsibly(deleted_keys, get_master_snapshots_map(store()), snap_name);
These changes address issue #227

2023-04-24 15:44 UTC, qc00 commented on python/tests/unit/arcticdb/version_store/test_index_ordering.py
What's with the line feeds?

2023-04-25 10:43 UTC, alexowens90 commented on python/tests/unit/arcticdb/version_store/test_index_ordering.py
(I didn't mean to add this file, will remove)
The CLion licensing auto-add plugin is not perfect...

2023-05-03 17:07 UTC, willdealtry requested changes

2023-05-09 13:07 UTC, vasil-pashov commented on cpp/arcticdb/pipeline/query.hpp
> +    ReadQuery(){}
Why not:
```suggestion
    ReadQuery() = default;
```

2023-05-09 13:08 UTC, vasil-pashov commented on cpp/arcticdb/pipeline/query.hpp
> +    ReadQuery(std::vector<Clause>&& query)
I'd mark it as explicit just in case.

2023-05-09 14:05 UTC, alexowens90 commented on cpp/arcticdb/processing/clause.hpp
> +    using Members = folly::PolyMembers<&T::process, &T::repartition, &T::requires_repartition, &T::execution_context, &T::can_combine_with_column_selection>;
Yeh I'm struggling to come up with something more concise. It means that the clause is compatible with passing the `columns` argument to `read` (or similar). e.g. it makes no sense to pass `columns` to `read` with a groupby/aggregation `QueryBuilder`.
It is needed to narrow down the number of data segments read from storage when doing column stats generation and groupbys, previously all data segments were always read.

2023-05-09 14:11 UTC, alexowens90 commented on cpp/arcticdb/processing/aggregation_interface.hpp
> +struct IColumnStatsAggregatorData {
With the processing pipeline refactor, the idea is to replace `IAggregation` with `IAggregatorData` and `IAggregator` (i.e. separate non-const from const portions), and possibly even homogenise so there is no distinction between the interface for general aggregations and column stats aggregations, so I'd rather leave it here for this PR.

2023-05-09 14:17 UTC, alexowens90 commented on cpp/arcticdb/pipeline/read_pipeline.hpp
> -    if(!(dynamic_schema && !column_groups))
No behaviour change, pretty sure it is correct

2023-05-09 14:28 UTC, qc00 approved these changes

2023-05-09 14:34 UTC, willdealtry commented on cpp/arcticdb/processing/clause.hpp
> +    using Members = folly::PolyMembers<&T::process, &T::repartition, &T::requires_repartition, &T::execution_context, &T::can_combine_with_column_selection>;
Right, fair enough it is a bit niche

2023-05-10 10:18 UTC, willdealtry approved these changes

2023-05-10 10:18 UTC, willdealtry approved these changes

2023-05-10 10:21 UTC, merged