Implementation for Decimal type with memory layout compatible with pyarrow's memory layout.
man-group/ArcticDB pull request #341
Opened 2023-05-05 16:27 UTC by vasil-pashov

* Load decimal from string
* Convert decimal to string
* Check for equality
* Add unit tests

Implementation is for 128 bit fixed point decimal. The number is stored as two little endian uint64_t variables. The format does not store the position of the decimal point.

2023-05-05 16:32 UTC, vasil-pashov commented on cpp/arcticdb/util/decimal.cpp
> +            boost::multiprecision::uint128_t number = to_uint128(
This also uses boost's implementation as intermediate type. Again we could change this if needed at the cost of having a bit more complicated code.

2023-05-05 16:33 UTC, vasil-pashov commented on cpp/arcticdb/util/preprocess.hpp
> -#define to_id(x) ([]() constexpr { return x; })
This was not used anywhere but for some reason makes the build to fail.

2023-05-09 09:38 UTC, vasil-pashov commented on cpp/arcticdb/util/decimal.cpp
> +        Decimal::Decimal(std::string_view number) : data_{0} {
I went with custom linear parsing, but regex might be a better idea. Any opinions?

2023-05-11 07:55 UTC, willdealtry requested changes

2023-05-11 07:56 UTC, willdealtry approved these changes

2023-05-11 08:45 UTC, vasil-pashov commented on cpp/arcticdb/util/decimal.cpp
> +            std::string result;
Yes, it's possible. I was thinking that for most of the cases we have the SSO will kick in. `sizeof(std::string)` is 32bytes, so about 30 chars, should fit it without allocation. If we do `result.reserve` we will be allocating always (I think).

2023-05-11 12:04 UTC, merged