Move encoded field and descriptors from protobuf
man-group/ArcticDB pull request #401
Opened 2023-05-18 18:11 UTC by willdealtry

Move encoded fields and stream descriptors out of protobuf

2023-05-23 09:30 UTC, mehertz commented
![image](https://github.com/man-group/ArcticDB/assets/3106180/006ef38a-7155-426b-b043-0e51f5d532a3)

Can you please add the **full set of changes to the PR descriptionI**. A real quick glance shows that you are changing our dependency from `asan` to `tsan` for example so I'm guessing there are further small unrelated changes throughout.

2023-05-23 16:42 UTC, qc00 commented on cpp/arcticdb/async/async_store.hpp
> +            const auto &key = keys[i];
The variable is only used once, so might as well do `std::move(keys[i])` for efficiency?

2023-05-23 16:42 UTC, qc00 commented on cpp/arcticdb/async/base_task.hpp
It might make this PR more reviewable if you can exclude these file mode changes.

2023-05-23 16:42 UTC, qc00 commented on cpp/arcticdb/async/base_task.hpp
It might make this PR more reviewable if you can exclude these file mode changes.

2023-05-23 16:54 UTC, mehertz requested changes

2023-05-25 08:36 UTC, willdealtry commented on cpp/arcticdb/CMakeLists.txt
> +                #asan
These have been there since forever so you can turn on sanitizers with a quick find and replace. I guess I''ll replace them with a cmake flag.

2023-06-05 09:02 UTC, mehertz requested changes
Document the new library setting

2023-06-05 15:37 UTC, mehertz requested changes

2023-06-05 15:37 UTC, mehertz commented on python/arcticdb/exceptions.py
These have still been ch-modded.

2023-06-05 16:03 UTC, willdealtry reviewed
Commented on things

2023-06-12 09:27 UTC, mehertz requested changes
What error will be thrown if an old client reads new data? Please paste the error!

2023-06-29 15:33 UTC, alexowens90 approved these changes

2023-06-30 09:31 UTC, mehertz approved these changes

2023-06-30 12:07 UTC, merged